

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
  namespace: lucky-namespace
  labels:
    app: lucky-numberz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage


---


apiVersion: v1
kind: Service
metadata:
  name: lucky-numberz-db
  namespace: lucky-namespace
  labels:
    app: lucky-numberz
spec:
  ports:
    - port: 3306
  selector:
    app: lucky-numberz
    tier: mysql
  clusterIP: None


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucky-numberz-db
  namespace: lucky-namespace
  labels:
    app: lucky-numberz
spec:
  selector:
    matchLabels:
      app: lucky-numberz
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lucky-numberz
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-volume-claim



---

