apiVersion: v1
kind: Service
metadata:
  name: lucky_numberz-back-end
  namespace: lucky-namespace
  labels:
    app: lucky_numberz-back-end-service
spec:
  type: NodePort
  selector:
    app: lucky_numberz-back-end-service
  ports:
  - name: http
    port: 8111
    protocol: TCP
    targetPort: 9111
  sessionAffinity: None

