name: Development Branch Merge

on:
  push:
    branches: 
      - development
      

jobs:
  test:
    name: Testing Merge to Development Branch
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Printing Git Branch
      run: git branch
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Verify with Maven, Scan with Sonar
      run: |
        mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      
  docker:
      name: Docker build and push
      runs-on: ubuntu-latest
      needs: [test]
      
      steps:    
        - uses: actions/checkout@v1
        - name: Installing GitVersion
          uses: gittools/actions/gitversion/setup@v0.9
          with:
              versionSpec: '5.1.x'
        - name: Use GitVersion
          id: gitversion
          uses: gittools/actions/gitversion/execute@v0.9
        - name: Setting Version Number
          run: |
            mvn versions:set -DnewVersion=${{ steps.gitversion.outputs.semVer }}-SNAPSHOT
        - name: Maven Package
          run: |
            mvn package 
        - name: Target Contents
          run: |
            ls target
        - name: Login to Docker
          run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PWD }}
        - name: Build Docker Image
          run: |
            RELEASE_TAG=${{ steps.gitversion.outputs.semVer }}
            docker build --build-arg release_version=$RELEASE_TAG -t lucky_numbers:$RELEASE_TAG -t ${{ secrets.DOCKER_USER }}/lucky_numbers:$RELEASE_TAG . 
        - name: Publish Docker image
          run: |
            RELEASE_TAG=${{ steps.gitversion.outputs.semVer }}
            docker push ${{ secrets.DOCKER_USER }}/lucky_numbers:$RELEASE_TAG
            echo "Pushed Docker Image with New Release"
        - name: Upgrading Version
          run: |
            RELEASE_TAG=${{ steps.gitversion.outputs.semVer }}
            echo $RELEASE_TAG > version.ver
            git add .
            git commit -m "Upgraded Version >> $RELEASE_TAG"




